---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-vulcand-router
  labels:
    name: k8s-vulcand-router
    # verify: k8s-vulcand-router
spec:
  replicas: 3
  selector:
    name: k8s-vulcand-router
  template:
    metadata:
      labels:
        name: k8s-vulcand-router
        # verify: k8s-vulcand-router
    spec:
      containers:
      - name: relay
        image: nordstrom/kubernetes-vulcand-router:0.1.0-dev
        imagePullPolicy: Always
        args: 
          - "-apiserver=http://25.0.0.1"
          - "-vulcand=http://127.0.0.1:8182"
      - name: router
        image: mailgun/vulcand:v0.8.0-beta.2
        args: 
          - "/go/bin/vulcand"
          - "--etcd=http://127.0.0.1:2379"
          - "-interface=0.0.0.0"
          - "-port=8181"
          - "-apiInterface=0.0.0.0"
          - "-apiPort=8182"
          - "-log=console"
          - "-logSeverity=INFO"
        ports:
          - containerPort: 8181
            name: vulcand-http
          - containerPort: 8182
            name: vulcand-api
        livenessProbe:
          httpGet:
            # Path to probe; should be cheap, but representative of typical behavior
            path: /status/v2
            port: 8182
          initialDelaySeconds: 30
          timeoutSeconds: 1
      - name: etcd
        image: quay.io/coreos/etcd:v2.2.1
        args: 
          - "--data-dir=/var/lib/etcd"
          - "--advertise-client-urls=http://127.0.0.1:2379"
          - "--listen-client-urls=http://127.0.0.1:2379"
          - "--listen-peer-urls=http://127.0.0.1:2380"
          - "--name=k8s-vulcand-router-etcd"
        ports:
          - name: etcd-http
            containerPort: 2379
          - name: etcd-peer
            containerPort: 2380
        # livenessProbe:
        #   httpGet:
        #     # Path to probe; should be cheap, but representative of typical behavior
        #     path: /status/v2
        #     port: 2379
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1
