---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-vulcand-router-rc
  labels:
    name: k8s-vulcand-router
    # verify: k8s-vulcand-router
spec:
  replicas: 3
  selector:
    name: k8s-vulcand-router
  template:
    metadata:
      labels:
        name: k8s-vulcand-router
        # verify: k8s-vulcand-router
    spec:
      containers:
        - name: k8s-vulcand-router-relay
          image: nordstrom/kubernetes-vulcand-router:0.0.1
          args: 
            - "-etcd=http://127.0.0.1:2379"
            - "-apiserver=http://25.0.0.1:8080"
        - name: k8s-vulcand-router
          image: nordstrom/vulcand:0.8.0-beta.2
          args: 
            - "--etcd=http://127.0.0.1:2379"
            - "-interface=0.0.0.0"
            - "-port=8181"
            - "-apiInterface=0.0.0.0"
            - "-apiPort=8182"
            - "-log=console"
            - "-logSeverity=WARN"
          ports:
            - containerPort: 8181
            - containerPort: 8182
        - name: k8s-vulcand-router-etcd
          image: quay.io/coreos/etcd:v2.2.1
          args: 
            - "--data-dir=/var/lib/etcd"
            - "--advertise-client-urls=http://127.0.0.1:2379"
            - "--listen-client-urls=http://127.0.0.1:2379"
            - "--listen-peer-urls=http://127.0.0.1:2380"
            - "--name=k8s-vulcand-router-etcd"
          ports:
            - containerPort: 2379
            - containerPort: 2380
