---
apiVersion: v1
kind: Service
metadata:
  name: k8s-vulcand-router
  labels:
    name: k8s-vulcand-router
    # verify: kubernetes-vulcand-router
spec:
  type: NodePort 
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31901
    protocol: TCP
  selector:
    name: k8s-vulcand-router
